//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autoservice_dataservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointments()
        {
            this.Invoices = new HashSet<Invoices>();
        }
    
        public int AppointmentID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string Status { get; set; }
        public int ClientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices> Invoices { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Services Services { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
